### ISSUE TITLE
Error returned when using gsn start

### ISSUE THREAD

**Issue by nots29vv** [forshtat/gsn-approver#1]
"Error: number can not store up to 53 bits" is returned after naive paymaster is funded. Due to this I never get to run gsn on my local Host..please help
![IMG_20210528_042113_7](https://user-images.githubusercontent.com/83395635/120001362-9e4c5100-bfcb-11eb-8def-ee0e237a699d.jpg)

**Comment by forshtat** [comment]
Hello @nots29vv and thanks for reporting. 

Unfortunately this repository is not a GSN repository. The correct repository to report issues to is https://github.com/opengsn/gsn

Indeed there were some issues with `gsn start` so last release did not include this command. Hopefully it will be fixed in the next few days.

**Comment by forshtat** [comment]
https://github.com/opengsn/gsn/pull/648
